### ISSUE TITLE
Only register if your envars are set

### ISSUE THREAD

**Issue by ntindle** [ppetermann/AutoGPTMastodonPlugin#1]
https://github.com/ppetermann/AutoGPTMastodonPlugin/blob/3757002ae95ceba84037520faae43a220941605a/src/auto_gpt_mastodon_plugin/__init__.py#L39

**Comment by ppetermann** [comment]
I'm actually checking that at runtime, creating appropriate error messages if they aren't set, why would preventing register be better?
